name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true

      - name: Install
        run: vp install

      - name: Lint
        run: vp lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pinia-version: [3, 4]
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true

      - name: Install base deps
        run: vp install

      - name: Override Pinia version
        run: |
          vp add pinia@${{ matrix.pinia-version }}

      - name: Build
        run: vp pack

      - name: Test
        run: vp test
